# Generated by Django 5.0 on 2023-12-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('bug_report_website', 'Report Bug in Website'), ('bug_report_app', 'Report Bug in App'), ('subscription_issue', 'Amount Deducted but Subscription Not Activated'), ('new_store_request', 'Request to Add New Store in Price History'), ('feedback', 'Feedback'), ('others', 'Others')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
