# Generated by Django 4.2.8 on 2024-01-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='price',
            field=models.TextField(),
        ),
    ]
