# Generated by Django 4.2.8 on 2024-01-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0005_alter_wishlist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='no_of_ratings',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='ratings',
            field=models.TextField(),
        ),
    ]
