# Generated by Django 4.2.8 on 2024-01-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0006_alter_wishlist_no_of_ratings_alter_wishlist_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
