# Generated by Django 4.2.8 on 2024-01-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0007_wishlist_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
