# Generated by Django 4.2.8 on 2024-01-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0009_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='favorite',
        ),
    ]
