# Generated by Django 4.2.8 on 2024-01-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0010_remove_wishlist_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='set_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_of_ratings',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.TextField(),
        ),
    ]
