# Generated by Django 4.2.8 on 2024-01-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0012_product_source_alter_product_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.TextField(default='NULL'),
        ),
    ]
