# Generated by Django 4.2.8 on 2024-01-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0013_alter_product_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='set_images/'),
        ),
    ]
