# Generated by Django 4.2.8 on 2024-01-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='set_images/'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='product_images/'),
        ),
    ]
