# Generated by Django 4.2.8 on 2024-01-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0016_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='link',
            field=models.URLField(max_length=2000),
        ),
    ]
