# Generated by Django 4.2.8 on 2024-01-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0017_alter_product_link_alter_wishlist_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('feature_request', 'Feature Request'), ('price_discrepancy', 'Price Discrepancy Report'), ('account_support', 'Account Support'), ('partnership_inquiry', 'Partnership Inquiry'), ('data_accuracy_issue', 'Data Accuracy Issue'), ('user_experience_feedback', 'User Experience Feedback'), ('others', 'Others')], max_length=50),
        ),
    ]
