# Generated by Django 4.2.8 on 2024-01-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0019_alter_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField()),
            ],
        ),
    ]
