# Generated by Django 4.2.8 on 2024-01-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmate', '0020_recentsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='trackmate/images/profile_photo.png', null=True, upload_to='profile_photos/'),
        ),
    ]
